/* Generated By:JavaCC: Do not edit this line. ICCParserConstants.java */
package chessclub.com.icc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ICCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int STRLIT = 7;
  /** RegularExpression Id. */
  int GE = 8;
  /** RegularExpression Id. */
  int LE = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int NE = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int OPAREN = 17;
  /** RegularExpression Id. */
  int CPAREN = 18;
  /** RegularExpression Id. */
  int MULT = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<NUMBER>",
    "<ID>",
    "<STRLIT>",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
    "<NE>",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
  };

}
