package chessclub.com.icc;

//import static org.junit.Assert.*;

import static org.junit.Assert.assertEquals;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import chessclub.com.enums.CN;

/**
 * 
 * @author David Logan
 * 
 *         Test class
 * 
 */
public class CNTEST {

    public CNTEST() {
    }

    /**
     * 
     * @throws Exception
     *             If an Exception occurs
     */
    @Before
    public final void setUp() throws Exception {
    }

    /**
     * 
     * @throws Exception
     *             If an Exception occurs
     */
    @After
    public final void tearDown() throws Exception {
    }

    /**
       * 
       */
    @Test
    public final void testEmAll() {
        for(int x=0;x<testList.length / 2 ; x++) {
            CN cn = (CN)testList[x*2];
            int v = (Integer)testList[x*2+1];
            assertEquals(cn.toString()+" was supposed to be " + cn.getValue() + " but was " + v, v, cn.getValue());
        }
    }

    Object[] testList = new Object[]{
            CN.ABORT,156,
            CN.ABORTADJ,231,
            CN.ACCEPT,123,
            CN.ACCEPT0,68,
            CN.ACCESS0,88,
            CN.ACCOUNT,358,
            CN.ADDCOMMENT,312,
            CN.ADDPLAYER,315,
            CN.ADDRESS,313,
            CN.ADJOURN,134,
            CN.ADJUDICATE,302,
            CN.ADMIN,300,
            CN.ADMIN_UN,301,
            CN.ALLOBSERVERS,157,
            CN.ALLOBSERVERS0,84,
            CN.ALLOCS,318,
            CN.ANNOTATE,257,
            CN.ARROW,226,
            CN.ASET,303,
            CN.ASET0,304,
            CN.ASSESS,135,
            CN.ATELL,362,
            CN.AWAY,219,
            CN.AWHO,305,
            CN.BACK,120,
            CN.BACK0,70,
            CN.BAD,112,
            CN.BELL,142,
            CN.BEST,161,
            CN.BEST0,76,
            CN.BLANKING,227,
            CN.BOARDINFO,292,
            CN.BOGOMODE,325,
            CN.BROADCAST,309,
            CN.BUGWHO,202,
            CN.CC_ASK_DIRECTOR,243,
            CN.CC_DELETE,237,
            CN.CC_LIST,235,
            CN.CC_LIST0,69,
            CN.CC_MOVE,236,
            CN.CC_QADJUDICATE,242,
            CN.CC_QDELETE,241,
            CN.CC_QLABEL,240,
            CN.CC_QLIST,239,
            CN.CC_QSTART,238,
            CN.CC_START,234,
            CN.CENSOR,81  ,
            CN.CENSOR0,82  ,
            CN.CHANNELQTELL,211,
            CN.CHANNELTELL,110,
            CN.CHECK_SPEAK,377,
            CN.CIRCLE,225,
            CN.CLEARBOARD,258,
            CN.CLEARMESSAGES,176,
            CN.CLEARMESSAGES0,73 ,
            CN.COMMANDS,221,
            CN.COMMENTGAME,360,
            CN.COMPLAIN,287,
            CN.COOKIE,326,
            CN.COOKIE0,327,
            CN.COPYGAME,118,
            CN.COPYGAME0,117,
            CN.C_ACCEPT,338,
            CN.C_ACCRUED,343,
            CN.C_BUY,345,
            CN.C_CLEAR,344,
            CN.C_DECLINE,339,
            CN.C_HISTORY,337,
            CN.C_ISSUE,341,
            CN.C_OFFER,335,
            CN.C_PAY,342,
            CN.C_PENDING,334,
            CN.C_REFUND,340,
            CN.C_WITHDRAW,336,
            CN.DATE,177,
            CN.DEBUG,372,
            CN.DECLINE,144,
            CN.DRAW,207,
            CN.DRAWADJ,230,
            CN.DUMP,329,
            CN.ECO,140,
            CN.ECO0,93,
            CN.EVENTS,271,
            CN.EXAMINE,115,
            CN.EXAMINE0,72,
            CN.EXPUNGE,184,
            CN.EXTEND,188,
            CN.EXTEND_PART,323,
            CN.FEN,264,
            CN.FINDADDRESS,314,
            CN.FINDIP,330,
            CN.FINDNAME,331,
            CN.FINGER,130,
            CN.FINGER0,90,
            CN.FIRSTMOVE_QUEUE,91,
            CN.FIVEMINUTE,284,
            CN.FLAG,108,
            CN.FLIP,182,
            CN.FLUSH,354,
            CN.FOLLOW,139,
            CN.FOLLOW0,138,
            CN.FORCEREGISTER,316,
            CN.FORFEITADJOURNED,357,
            CN.FORWARD,119,
            CN.FORWARD0,71,
            CN.GAMEID,283,
            CN.GAMES,155,
            CN.GAMES0,85,
            CN.GBEST,281,
            CN.GDESCRIBE,279,
            CN.GETPS,394,
            CN.GETPX,245,
            CN.GINVITE,275,
            CN.GIVE_TICKET,332,
            CN.GJOIN,276,
            CN.GKICK,280,
            CN.GLISTGROUPS,273,
            CN.GLISTINVITED,277,
            CN.GLISTJOINING,278,
            CN.GLISTMEMBERS,274,
            CN.GMESSAGE,286,
            CN.GOTO,192,
            CN.HELP,125,
            CN.HELP0,124,
            CN.HISTORY,129,
            CN.HISTORY0,94,
            CN.I,102,
            CN.INCHANNEL,158,
            CN.INCHANNEL0,83  ,
            CN.INFO,159,
            CN.INFO0,80,
            CN.ISREGNAME,255,
            CN.IWCMATCH,185,
            CN.KEEPGAME,322,
            CN.KIBITZ,113,
            CN.KIBITZ_TO,87,
            CN.LAGSTATS,220,
            CN.LASTTELLS,288,
            CN.LHISTORY,165,
            CN.LIBANNOTATE,197,
            CN.LIBDELETE,196,
            CN.LIBKEEPEXAM,198,
            CN.LIBLIST,194,
            CN.LIBSAVE,195,
            CN.LIMITS,186,
            CN.LIST,178,
            CN.LLOGONS,164,
            CN.LOADFEN,244,
            CN.LOADGAME,229,
            CN.LOGPGN,262,
            CN.LOUDSHOUT,307,
            CN.MAILHELP,153,
            CN.MAILNEWS,232,
            CN.MAILOLDMOVES,151,
            CN.MAILPASSWORD,319,
            CN.MAILSTORED,152,
            CN.MATCH,121,
            CN.MATCH0,122,
            CN.MESSAGE,174,
            CN.MESSAGE0,175,
            CN.MEXAMINE,116,
            CN.MINUS,180,
            CN.MORE,126,
            CN.MORETIME,160,
            CN.MOVES,150,
            CN.NEWS,127,
            CN.NEWS0,128,
            CN.NORELAY,247,
            CN.NUKE,306,
            CN.OBSERVE,137,
            CN.OBSERVE0,136,
            CN.OPEN,143,
            CN.PARTNER,199,
            CN.PARTNER0,200,
            CN.PASSWORD,173,
            CN.PAYFAILURE,369,
            CN.PAYMENT,324,
            CN.PENDING,154,
            CN.PERSONALINFO,270,
            CN.PGN,249,
            CN.PHRASELIST,373,
            CN.PHRASEPTELL,375,
            CN.PHRASESAY,376,
            CN.PHRASETELL,374,
            CN.PING,187,
            CN.PLAY,217,
            CN.PLAYERS,97,
            CN.PLUS,179,
            CN.PRIMARY,206,
            CN.PROMOTE,183,
            CN.PSTAT,291,
            CN.PTELL,201,
            CN.QADDEVENT,272,
            CN.QFOLLOW,251,
            CN.QIMPART,285,
            CN.QIMPART,285 ,
            CN.QMATCH,253,
            CN.QPARTNER,254,
            CN.QRETRACT,367,
            CN.QSET,233,
            CN.QSUGGEST,350,
            CN.QTELL,189,
            CN.QUERYUI,365,
            CN.QUIT,162,
            CN.QUIT_PLAY,79,
            CN.QUNFOLLOW,252,
            CN.QUOTA,163,
            CN.QUOTA0,78        ,
            CN.RANK,149,
            CN.RATED,148,
            CN.RATING,352,
            CN.REFER,248,
            CN.REFRESH,145,
            CN.REGENTRY,269,
            CN.REGISTER,223,
            CN.REHASH,320,
            CN.RELAY,228,
            CN.REMATCH,222,
            CN.REMGAME,311,
            CN.REMPLAYER,321,
            CN.REQUEST_ABORT,261,
            CN.REQUEST_DRAW,260,
            CN.REQUEST_WIN,259,
            CN.REQUIRETICKET,256,
            CN.RESIGN,208,
            CN.RESIGNADJ,146,
            CN.RESTRICT,370,
            CN.RESULT,263,
            CN.RESUME,224,
            CN.REVERT,147,
            CN.R_RATING,361,
            CN.SAY,109,
            CN.SEARCH,169,
            CN.SEARCH0,170,
            CN.SEEKING,214,
            CN.SET,107,
            CN.SET2,216,
            CN.SETCLOCK,193,
            CN.SETGAMEPARAM,266,
            CN.SET_OTHER,371,
            CN.SFEN,265,
            CN.SHOUT,103,
            CN.SHOUT0,104,
            CN.SHOWADMIN,290,
            CN.SHOW_ALL_OPEN_FDS,317,
            CN.SHUTDOWN,310,
            CN.SIMULIZE,282,
//            CN.SIZE,400,
            CN.SJIAD,366,
            CN.SLASH,105,
            CN.SMOVES,171,
            CN.SNUBBING,359,
            CN.SOUGHT,215,
            CN.SPGN,250,
            CN.SPOOF,328,
            CN.SPOSITION,172,
            CN.SQL,368,
            CN.SSHOUT,111,
            CN.STARTSIMUL,191,
            CN.STATISTICS,209,
            CN.STORED,210,
            CN.STORED0,75,
            CN.STYLE,141,
            CN.TAG,267,
            CN.TAKEBACK,168,
            CN.TAKEBACK0,74 ,
            CN.TAKE_TICKET,333,
            CN.TELL,101,
            CN.TELL0,96,
            CN.TELLUNREG,308,
            CN.TELL_DOT,99,
            CN.TEST,353,
            CN.THREEMIN,92,
            CN.TIME,167,
            CN.TIME0,95,
            CN.TOMOVE,268,
            CN.UNCOMMENT,363,
            CN.UNEXAMINE,133,
            CN.UNRELAYED,246,
            CN.UNSEEKING,218,
            CN.UPSTATISTICS,132,
            CN.VARS,131,
            CN.VARS0,89,
            CN.VIEW,289,
            CN.WHISPER,114,
            CN.WHISPER_TO,86,
            CN.WHO,106,
            CN.WHO0,98,
            CN.WILDRANK,204,
            CN.WSUGGEST,364,
            CN.XOBSERVE,205,
            CN.XPARTNER,212,
            CN.XTELL,100,
            CN.YFINGER,213,
            CN.ZNOTL,181,
            CN.S_ACK_PING,30,
            CN.S_AUTHENTICATION,24,
            CN.S_AUTOMATIC,26,
            CN.S_BAD,25,
            CN.S_CONFIRM,27,
            CN.S_CONNECT,18,
            CN.S_EDIT_EXAMINED,3,
            CN.S_EVENTS,14,
            CN.S_EXTENSION,23,
            CN.S_IDLE,29,
            CN.S_ILLEGAL_MOVE,1,
            CN.S_LOGIN,20,
            CN.S_LOGOUT,16,
            CN.S_MISCELLANEOUS,31,
            CN.S_MOED,13,
            CN.S_MOVE,2,
            CN.S_MULTI_DISCARD,28,
            CN.S_NEWS,15,
            CN.S_PASSWORD,21,
            CN.S_PING_RESPONSE,10,
            CN.S_REALLY_LOG_IN,12,
            CN.S_REALLY_QUIT,19,
            CN.S_REGISTRATION,22,
            CN.S_TIMEOUT,17,
            CN.S_UNKNOWN,0,
            CN.S_WEIRD,11,
    };
}
