/* Generated By:JavaCC: Do not edit this line. PGNParserConstants.java */
package david.logan.chess.support.pgn.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PGNParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int LINECOMMENT = 10;
  /** RegularExpression Id. */
  int STRLIT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int PERIOD = 13;
  /** RegularExpression Id. */
  int LBRACKET = 14;
  /** RegularExpression Id. */
  int RBRACKET = 15;
  /** RegularExpression Id. */
  int OPAREN = 16;
  /** RegularExpression Id. */
  int CPAREN = 17;
  /** RegularExpression Id. */
  int GAMETERM = 18;
  /** RegularExpression Id. */
  int MOVE = 19;
  /** RegularExpression Id. */
  int TAGNAME = 20;
  /** RegularExpression Id. */
  int CASTLE = 21;
  /** RegularExpression Id. */
  int NAG = 22;
  /** RegularExpression Id. */
  int ANNOTATION = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"{\"",
    "<COMMENT>",
    "\"}\"",
    "\";\"",
    "<SINGLE_LINE_COMMENT>",
    "<LINECOMMENT>",
    "<STRLIT>",
    "<INTEGER>",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<GAMETERM>",
    "<MOVE>",
    "<TAGNAME>",
    "<CASTLE>",
    "<NAG>",
    "<ANNOTATION>",
  };

}
