/* Generated By:JavaCC: Do not edit this line. JudgeBotCommandParserConstants.java */
package chessclub.com.icc.jb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JudgeBotCommandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HELP = 9;
  /** RegularExpression Id. */
  int STATUS = 10;
  /** RegularExpression Id. */
  int SUMMARY = 11;
  /** RegularExpression Id. */
  int WIN = 12;
  /** RegularExpression Id. */
  int NOWIN = 13;
  /** RegularExpression Id. */
  int INFO = 14;
  /** RegularExpression Id. */
  int LOSE = 15;
  /** RegularExpression Id. */
  int NOLOSE = 16;
  /** RegularExpression Id. */
  int RUNTIME = 17;
  /** RegularExpression Id. */
  int MEMORY = 18;
  /** RegularExpression Id. */
  int OS = 19;
  /** RegularExpression Id. */
  int LASTTELLS = 20;
  /** RegularExpression Id. */
  int RESETMSG = 21;
  /** RegularExpression Id. */
  int KILLGAME = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int STRLIT = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int AFTER_KEYWORD = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"help\"",
    "\"status\"",
    "\"summary\"",
    "\"win\"",
    "\"nowin\"",
    "\"info\"",
    "\"lose\"",
    "\"nolose\"",
    "\"runtime\"",
    "\"memory\"",
    "\"os\"",
    "\"lasttells\"",
    "\"resetmsg\"",
    "\"killgame\"",
    "<ID>",
    "<NUMBER>",
    "<STRLIT>",
  };

}
